name: Publish to GitHub npm Registry

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

    #   - name: Configure git
    #     run: |
    #       git config user.name "${GITHUB_ACTOR}"
    #       git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: 'https://npm.pkg.github.com/'

      - name: Clean install dependencies
        run: npm ci

      - name: Extract version from tag
        id: extract_version
        run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Update package.json version if needed
        run: |
          version=${{ steps.extract_version.outputs.version }}
          current_version=$(node -p "require('./package.json').version")
          if [ "$version" != "$current_version" ]; then
            npm version --no-git-tag-version "$version"
          else
            echo "Version already set to $version, skipping npm version."
          fi

      - name: Publish to GitHub npm registry
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm publish --registry=https://npm.pkg.github.com/
